#!/bin/bash
#

set -e
set -o pipefail

export PATH=$PATH:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:.
. <( arv-dax setup )

mntdir=`arv-dax keep`
jobparam=`arv-dax script_parameters`

icol=$mntdir/`echo "$jobparam" | jq -r '.INPUT_COLLECTION'`/output
REPORTID=`echo "$jobparam" | jq -r '.REPORT_ID'`

echo ">>>>>>>>>>>>>>>>>>>>> COPYING $icol/get-evidence.json to ., $CRUNCH_SRC/crunch-scripts/html ."

cp -R $CRUNCH_SRC/crunch_scripts/html/* .
#cp -R $icol/out-data/get-evidence.json .
cp -R $icol/out-data/* .

$CRUNCH_SRC/crunch_scripts/repl.py "$REPORTID" < ./get-evidence-report.template > get-evidence-report.html

# Workbench sort files by most recently used?
# Update more relevant files to have them
# show up at the top.
touch -c get-ev_genes.json
touch -c ns.gff.gz
touch -c get-evidence.json
touch -c get-evidence-report.html

arv-dax task finish
exit 0
