#!/bin/bash
#

set -e
set -o pipefail

export PATH=$PATH:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:.
. <( arv-dax setup )

mntdir=`arv-dax keep`
jobparam=`arv-dax script_parameters`

icol=$mntdir/`echo "$jobparam" | jq -r '.INPUT_COLLECTION'`

echo ">>>>>>>>>>>>>>>>>>>>> COPYING $icol/get-evidence.json to ., $CRUNCH_SRC/crunch-scripts/html ."

cp -R $CRUNCH_SRC/crunch_scripts/html/* .
#cp -R $icol/out-data/get-evidence.json .
cp -R $icol/out-data/* .

arv-dax task finish
exit 0
